### ISSUE TITLE
ValueError: PyCapsule_New called with null pointer

### ISSUE THREAD

**Issue by defp** [bttscut/pysproto#2]
改了 协议后就这样了，但是在项目里的lua版本跑的好好的

```

[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: Traceback (most recent call last):
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: result = self._run(*self.args, **self.kwargs)
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: File "/usr/local/lib/python2.7/site-packages/locust/runners.py", line 115, in start_locust
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: locust().run()
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: File "/Users/lidashuang/3pj/sproto-perf/locustfile_caocao.py", line 172, in __init__
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: timeout=timeout
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: File "/Users/lidashuang/3pj/sproto-perf/sproto_rpc_locust.py", line 45, in __init__
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: self.agent = SprotoRPC(c2s, s2c)
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: File "/Users/lidashuang/3pj/sproto-perf/sproto_rpc.py", line 10, in __init__
[2017-06-23 18:17:28,355] 3pj/ERROR/stderr: self._c2s = SprotoObj(c2s)
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr: File "/usr/local/lib/python2.7/site-packages/pysproto/sproto.py", line 7, in __init__
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr: self.sp = core.newproto(chunk)
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr: File "pysproto/core.pyx", line 245, in pysproto.core.newproto (pysproto/core.c:3746)
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr: ValueError: PyCapsule_New called with null pointer
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr: Fri Jun 23 18:17:28 2017
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr:
[2017-06-23 18:17:28,356] 3pj/ERROR/stderr: <Greenlet at 0x10efd12d0: start_locust(<class 'locustfile_caocao.CaoCaoLocust'>)> failed with ValueError
[2017-06-23 18:17:29,353] 3pj/INFO/locust.runners: All locusts hatched: CaoCaoLocust: 1
[2017-06-23 18:17:29,353] 3pj/INFO/locust.runners: Resetting stats

[2017-06-23 18:17:29,353] 3pj/INFO/locust.runners: All locusts dead
```

 ValueError: PyCapsule_New called with null pointer
这个是什么意思？“

**Comment by defp** [comment]
![image](https://user-images.githubusercontent.com/612381/27479781-dfb011bc-5847-11e7-91c5-933e7b2ad6bc.png)
找到导致问题的定义了

      msg 1 : string
 
这个在上面就不行，很奇怪

按理说写法应该没顺序的

**Comment by bttscut** [comment]
抱歉，写完后一直没跟进。

**Comment by bttscut** [comment]
我自己颠倒顺序测试了下，没有问题，能提供给我一个报错的协议么？呃。。。如果你还记得半年前的样子的话。

**Comment by defp** [comment]
算了，都跳槽了

**Comment by bttscut** [comment]
祝一切顺利。
